menu:
  home:
    title: Home
    url: /
  about:
    title: About
    url: /about
  browse:
    title: Browse
    url: /browse
  twitter:
    title: Twitter
    url: https://twitter.com/ygunayer
    icon: fa fa-twitter
  github:
    title: Github
    url: https://github.com/ygunayer
    icon: fa fa-github
  facebook:
    title: Facebook
    url: https://facebook.com/Yalin.Gunayer
    icon: fa fa-facebook
  linkedin:
    title: LinkedIn
    url: https://tr.linkedin.com/in/ygunayer
    icon: fa fa-linkedin


favicon: /favicon.png
logo: /favicon.png

mathjax: false

# comment
# e.g disqus: seansun
disqus: 
duoshuo: 

# google-analytics:
ga: 
# baidu-analytics:
ba: 

twitter: 'ygunayer'
